### ISSUE TITLE
Weather lag

### ISSUE THREAD

**Issue by mcandre** [freakified/TimeStylePebble#92]
Could we make the weather display more resilient, such as showing the last information known rather than a disconnect icon, when things go wrong?

The weather display often shows a Bluetooth connection disruption icon, instead of the last known weather status. This occurs even when the Bluetooth connection is actually solid, confirmed by Pebble settings, and getting live notifications from other apps.

**Comment by tilden** [comment]
It is actually 100% resilient, since it writes weather data to memory and it never, ever expires (in fact, it probably **should** expire, but that's issue #15)

The issue you're actually experiencing is simply that there's currently no way to disable the disconnect indication, which there really should be, especially because of situations like the one you describe where the Pebble thinks it's disconnected when it actually is just fine. This issue thus duplicates issue #65.
